---
- name: enable and start kafka
  service: name=kafka state=started enabled=yes

- name: wait for kafka port
  wait_for: host={{kafka_listen_address| default('localhost')}} port={{kafka_port}} state=started timeout=30
  when: verify
